### PR TITLE
chore!: set release level to GA

### PR DESCRIPTION
**Pull request by callmehiphop**
Not sure if this is the right commit message or how release-please knows to make minor bumps, but hopefully this does the trick!

### CODE REVIEW

**Review by bcoe — APPROVED** [review]

**Comment by alexander-fenster** [comment]
🎉 🎈

**Comment by alexander-fenster** [comment]
I would vote for `chore!:` in the title, there is no refactor here :)

**Review by JustinBeckwith — COMMENTED** [review]
So I'm not saying we _shouldn't_ do this, but I want to ask - how do you feel about the risk of breaking changes or stability with the ordered messaging PR?  That PR looks a little spicy, and I just want to make 100% sure we're not going to go GA, then find out we need to change the API again.

**Comment by callmehiphop** [comment]
@JustinBeckwith we've talked about that subject in the PubSub weekly meeting for a little while now and we're all in agreement that a surface change should not be necessary and I'm committed to that.

**Comment by kbariotis** [comment]
Hi everyone, I just wanted to ask, how is this a breaking change?

**Pull request merged**
