### PR TITLE
 docs(subscription): ensure sub options are not removed by ts

### LINKED ISSUE #684: doc: please describe`subscriberOptions`
It's not super clear by referencing the documentation whether the options we set for [`topic.subscription(name[, options])`](https://googleapis.dev/nodejs/pubsub/latest/Topic.html#subscription) and [`pubsub.subscription(name[, options])`](https://googleapis.dev/nodejs/pubsub/latest/PubSub.html#subscription) are the same. 

- Are they both of `type SubscriberOptions`? But one just tells me it's of `type object`. 
- Why does `type SubscriberOptions` get a description that says "Subscription options"?  
- Is there a link we can add to `type SubscriberOptions`? Which values can users pass to it?

### PR DESCRIPTION
**Pull request by callmehiphop**
Fixes #684

### CODE REVIEW

**Review by JustinBeckwith — APPROVED** [review]

**Review by anguillanneuf — COMMENTED** [review]
@callmehiphop Thanks for fixing this! How can I view the generated doc before approving?

**Comment by JustinBeckwith** [comment]
@anguillanneuf you would have to clone the forked branch, `npm run docs`, and then `open docs/index.html`.

**Comment by anguillanneuf** [comment]
@callmehiphop Nit: can we update the description for `subscriberOptions` [here](https://googleapis.dev/nodejs/pubsub/latest/PubSub.html#subscription) to `configuration object` as well?

**Comment by callmehiphop** [comment]
@anguillanneuf done!

**Review by anguillanneuf — APPROVED** [review]
LGTM! Once tests pass, please feel free to merge.

**Pull request merged**
