### PR TITLE
docs: fix documentation for publishing a message with an ordering key

### LINKED ISSUE #1435: Documentation is incorrect for publishing a message with orderingKey
https://github.com/googleapis/nodejs-pubsub/blob/main/samples/publishOrderedMessage.js#L69

`enableMessageOrdering` should be updated to `messageOrdering` according to the PublishOptions interface here https://github.com/googleapis/nodejs-pubsub/blob/98840fcc38a05be07de6e7dc97d8a79616940df9/src/publisher/index.ts#L38

### PR DESCRIPTION
**Pull request by a88zach**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [X] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-pubsub/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [X] Ensure the tests and linter pass
- [X] Code coverage does not decrease (if any source code was changed)
- [X] Appropriate docs were updated (if necessary)

Fixes #1435 🦕

### CODE REVIEW

**Comment by a88zach** [comment]
cla signed

**Comment by feywind** [comment]
@a88zach Sorry for the delay. I think the situation might be more complicated and less flattering than it looks at first glance. The `messageOrdering` field, as far as I can tell, despite being defined in interfaces, isn't actually used anywhere. It looks like that was replaced with server-side ordering into subscriptions. Does that sound right, @kamalaboulhosn ? There's also this, which isn't great:

```
    /**
     * Identifies related messages for which publish order should be respected.
     * If a `Subscription` has `enableMessageOrdering` set to `true`, messages
     * published with the same `orderingKey` value will be delivered to
     * subscribers in the order in which they are received by the Pub/Sub
     * system.
     *
     * **EXPERIMENTAL:** This feature is part of a closed alpha release. This
     * API might be changed in backward-incompatible ways and is not recommended
     * for production use. It is not subject to any SLA or deprecation policy.
     *
     * @name Message#orderingKey
     * @type {string}
     */
    this.orderingKey = message!.orderingKey!;
```

That's in subscription.ts.

**Comment by a88zach** [comment]
@feywind, I'm going to close this one since the discussion has gone stale

**Comment by jketcham** [comment]
For what it's worth, I just ran into this when looking into publishing ordered messages with the node library. [Examples](https://github.com/googleapis/nodejs-pubsub/blob/ac5e7ef8f8cf887a54eac27e8f88241036d9a8bf/samples/publishOrderedMessage.js#L69) use `enableMessageOrdering`, but type defines it as `messageOrdering`. Some resolution here at least on the type side would be nice.

**Pull request closed without merging**
