### PR TITLE
change maxMessages default to 100

### PR DESCRIPTION
**Pull request by callmehiphop**
Relates to https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2810

- [x] Tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Comment by jadekler** [comment]
👍 Might be worth updating documentation to recommend folks tune this variable per their needs

**Comment by jadekler** [comment]
Thanks @callmehiphop . Do you know when this will be released in a version I can try?

**Comment by stephenplusplus** [comment]
You can track the release in #112. If you're just looking to try it out, you can try right from master:

```sh
$ npm install --save googleapis/nodejs-pubsub
```

**Pull request merged**
