### PR TITLE
fix(subscriber): return a promise on close

### LINKED ISSUE #212: Subscriber/Subscription.close does not support promises
#### Environment details

  - OS: Linux
  - Node.js version: 7.5.0
  - npm version: 6.3.0
  - `@google-cloud/pubsub` version: 0.19.0

#### Steps to reproduce

  1. Call `subscription.close()` without a callback argument
  2. Expect to receive a promise per documentation
  3. No promise is returned

UTSL: The code for the Subscription class calls `promisifyAll` on its members, but `Subscriber`, where `close` is implemented, does not, and so close doesn't actually adhere to its JSdoc.

### PR DESCRIPTION
**Pull request by scragg0x**
Fixes #212

Not sure if this is the best way to fix, but here you go!

- [x] Tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Comment by scragg0x** [comment]
Sorry for the extra commits, probably want to squash if you merge.

**Comment by JustinBeckwith** [comment]
@callmehiphop can you take a look at this?

**Comment by callmehiphop** [comment]
@cragg0x sorry I kind of dropped the ball here, we actually have a [handy util](https://github.com/googleapis/nodejs-pubsub/blob/master/src/subscription.js#L729) for promisifying our methods. If you want to take a crack at getting that working here, that would be amazing! Otherwise I can totally tackle this

**Comment by scragg0x** [comment]
@callmehiphop You can go ahead and take this.  I didn't use the promisify lib since `close` calls 2 other async functions, one callback style and the other promise.

**Pull request closed without merging**
