### PR TITLE
Add TypeScript type definitions

### LINKED ISSUE #141: Convert to TypeScript
Currently blocked on https://github.com/googleapis/gapic-generator/issues/2054

### PR DESCRIPTION
**Pull request by BlueHatbRit**
Fixes #141.

This isn't quite a fix of course, I've not converted the entire module into TypeScript, however I have created a complete type definition for the entire public API of this module. I've based it upon the inline function definitions and the samples documentation.

My team really want to use this module rather than the full google API module, so I figured I'd spend an evening writing the types. I've not added any TS samples as I figured it probably wasn't quite needed due to the number of JS examples, inline docs, and the definitions file.

I've tried to keep type names the same as the inline docs, hopefully that helps people navigate them easily. There are a few places I've had to infer the types and names based on conventions. I'm happy to make changes if anyone can find any errors.

- [x] Tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Comment by BlueHatbRit** [comment]
It seems linters are failing on some "samples", since I've not changed them, I'm assuming that's not a problem for this PR. I'd be happy to try and update them if needed, but that could also perhaps be another PR.

**Comment by BlueHatbRit** [comment]
Working with our CEO to get the corporate CLA looked at, this could take a few days but I'll update here when it's done. Is there anyone I should ping once it's sorted?

**Comment by BlueHatbRit** [comment]
Yes my boss just got back from vacation, we'll be looking at getting this sorted this week. Apologies for the delay.

**Comment by moberemk** [comment]
Any updates on this? It seems like the current @types repository for this is out-of-date since it expects the root PubSub object to be a function and not a class.

**Comment by BlueHatbRit** [comment]
Hey there, sorry about the delay we've been utterly slammed the past few weeks. I've got this back on the radar and it's on the list to be done, I'm hoping it'll be sorted by this week.

**Comment by BlueHatbRit** [comment]
This should be all sorted now, could a google maintainer verify and merge please? :)

**Comment by BlueHatbRit** [comment]
Apologies for the "spam", the CLA has been signed by Gradient, I'm wondering if this can be merged or if there's a reason for the hold up? Just hoping this hasn't slipped through the net 😄

**Comment by marcusnielsen** [comment]
@BlueHatbRit Nice work getting the CLA! I think you should rebase to latest master to speed things up.

**Comment by BlueHatbRit** [comment]
Rebased as suggested

**Comment by BlueHatbRit** [comment]
Since this is adding types and not changing code, I can't see why the node11 or sample tests would be failing to run. The logs don't seem to reveal much that I could see being related to the types I've added. It seems the Samples test is failing on "publish with specific batch settings" which I can only assume is happening already on the master branch?

Can anyone shed some light on whether this is an issue with the PR?

**Comment by marcusnielsen** [comment]
Just to throw this out there: Should this be published via @types instead? Seems like @BlueHatbRit has done a great job, but not getting this merged.

**Comment by BlueHatbRit** [comment]
It would be good to give the maintainers first refusal on the types first. If we don't hear anything in a couple days, I'll publish a new module to @types to help tide people over until the maintainers have a chance to make a decision on this PR.

**Comment by JustinBeckwith** [comment]
Greetings folks, and apologies fr going dark on the thread here.  In fullness of time, we'd very much like to convert this library over to TypeScript.  In the interim...  having a d.ts would be awesome!  To reduce confusion though, I do think that having this over at DefinitelyTyped would be better.  I don't think we can maintain a hand crafted d.ts.  Thoughts on submitting this over there?

**Comment by BlueHatbRit** [comment]
This is fine by me, but I think it's useful to note here on this PR that it does mean the `.d.ts` file could go out of date very easily, without any tests or oversight from this team it would be very easy for things to diverge quickly. With that noted for future reference, there is already a DT package for this module (https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/google-cloud__pubsub) although it's quite out of date. I'll look at porting my types over to this one to update them instead.

Feel free to close this PR if needed.

**Comment by JustinBeckwith** [comment]
@BlueHatbRit thanks again for all the work here.  If the PR on DT doesn't work out (for whatever reason), let me know and we can revisit this.

**Pull request closed without merging**
