### PR TITLE
Fixed wrong documentation

### PR DESCRIPTION
**Pull request by lashae**
Publish with custom attributes resolves same as publish without custom attributes.

Fixes #<issue_number_goes_here> (it's a good idea to open an issue first for discussion)

- [ ] Tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Comment by lashae** [comment]
I signed the CLA.

**Comment by lashae** [comment]
I signed it!

**Comment by JustinBeckwith** [comment]
@fhinkel would you mind taking a look at this and seeing if it's correct?

**Comment by fhinkel** [comment]
@JustinBeckwith  How do I get the CLA to be green again? Does the label not work here?

**Comment by ofrobots** [comment]
I think the reason is this:

> Note to project maintainer: This is a terminal state, meaning the cla/google commit status will not change from this state. It's up to you to confirm consent of the commit author(s) and merge this pull request when appropriate.

At this point CLA bot is not going toggle the check status. We need to either 1) open a bug against the CLA bot 2) remove the 'required' status from the cla check, or 3) get an admin to merge PRs that end up in these situations. Since I have the admin powers, I am going to merge this.

**Comment by fhinkel** [comment]
My fault for missing a space in the label. Will merge as soon as the CIs are finished.

**Pull request merged**
