### PR TITLE
Fixes 177: Prevents publishing attributes that have non-string values

### LINKED ISSUE #177: Unhelp error message on invalid attributes
The `publish(message, attributes)` method in the `Publisher` class provides an unhelpful error message when the attributes object is specified _incorrectly_. It seems like the attribute object must only have values that are strings, Buffers, or ArrayBuffers. When the `attributes` is specified incorrectly, the Error in the rejected Promise is not very helpful:

```
TypeError: "string" must be a string, Buffer, or ArrayBuffer
    at Function.byteLength (buffer.js:481:11)
    at BufferWriter.write_string_buffer [as string] (/usr/local/google/home/nareddyt/workspace/untar-cloud-function/node_modules/protobufjs/src/writer_buffer.js:68:22)
    at Type.PubsubMessage$encode [as encode] (eval at Codegen (/usr/local/google/home/nareddyt/workspace/untar-cloud-function/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:11:15)
    at Type.encode_setup [as encode] (/usr/local/google/home/nareddyt/workspace/untar-cloud-function/node_modules/protobufjs/src/type.js:485:25)
    at BundleDescriptor.getByteLength [as byteLengthFunction] (/usr/local/google/home/nareddyt/workspace/untar-cloud-function/node_modules/google-gax/lib/grpc.js:269:20)
    at /usr/local/google/home/nareddyt/workspace/untar-cloud-function/node_modules/google-gax/lib/bundling.js:349:38
    at Array.forEach (<anonymous>)
    at BundleExecutor.schedule (/usr/local/google/home/nareddyt/workspace/untar-cloud-function/node_modules/google-gax/lib/bundling.js:348:16)
    at /usr/local/google/home/nareddyt/workspace/untar-cloud-function/node_modules/google-gax/lib/bundling.js:500:20
    at Canceller.call (/usr/local/google/home/nareddyt/workspace/untar-cloud-function/node_modules/google-gax/lib/api_callable.js:109:19)
```

Note that this error doesn't tell me:

- Which specific method parameter was incorrect
- Where in my original node.js module the error occurred (the stacktrace starts in a dependency)
- What the actual error message means (I thought to myself: "Why is a string not a actually string...?")

Additionally, the restriction on the `attributes` object is not documented in the [SDK docs for the method](https://cloud.google.com/nodejs/docs/reference/pubsub/0.18.x/Publisher#publish). This leads to further confusion when trying to debug this error.

#### Environment details

  - OS: gLinux
  - Node.js version: v8.11.0
  - npm version: 6.1.0
  - `@google-cloud/pubsub` version: 0.18.0

#### Steps to reproduce

Run the following code. Note here than I'm passing in a Boolean value in the `attributes` object, instead of a string. This would also occur if I pass in nested objects, an array, or null.

```
const PubSub = require('@google-cloud/pubsub');
const pubsub = new PubSub();
const topic = pubsub.topic(PUB_SUB_TOPIC_NAME);
const publisher = topic.publisher();

const message = Buffer.from('Hello World');
const attributes = {
  success: true,    // FIXME: This should be a string, not a boolean!
};

publisher.publish(message, attributes)
    .then(() => console.log('Done'))
    .catch(err => console.error(err));
```

### PR DESCRIPTION
**Pull request by nareddyt**
Fixes #177 

If the attributes object has non-string values, publishing fails.
This change adds extra checks to ensure all values are string typed.
Additionally, this precondition is documented.

Testing Done:
- [x] Added a new unit test and ran the test suite
- [x] Ensured the docs contain the new information
- [x] Checked code coverage
- [x] Ran eslint
- [x] Manual testing

### CODE REVIEW

**Comment by stephenplusplus** [comment]
@nareddyt sorry again that I missed this! Would you take a look at the commit I stacked on? Let me know if you object to any of the changes.

**Comment by nareddyt** [comment]
Ah those changes make the code much cleaner. Looks great :+1: 

Thanks for reviewing my code :)

**Comment by stephenplusplus** [comment]
Woo, great! @JustinBeckwith do you need to do a manual CLA-approval override?

**Comment by stephenplusplus** [comment]
Thanks, everyone!

**Pull request merged**
