### PR TITLE
fix: bind promisify calls for flush() so they have a 'this' value

### LINKED ISSUE #1178: Topic.flush() throws error
#### Environment details

  - OS: mac
  - Node.js version: 14.15.4
  - `@google-cloud/pubsub` version: 2.7.0

#### Steps to reproduce

```js
const { PubSub } = require('@google-cloud/pubsub')
const pubsub = new PubSub()
const topic = pubsub.topic('blah')
topic.flush().then(() => console.log('Flushed'), err => console.error('Error:', err))
```

Throws the following error:

```
> (node:5485) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'batch' of undefined
    at publish (<path>/node_modules/@google-cloud/pubsub/build/src/publisher/message-queues.js:99:46)
    at <path>/node_modules/@google-cloud/promisify/build/src/index.js:57:28
    at new Promise (<anonymous>)
    at wrapper (<path>/node_modules/@google-cloud/promisify/build/src/index.js:42:16)
    at Publisher.flush (<path>/node_modules/@google-cloud/pubsub/build/src/publisher/index.js:73:69)
    at Publisher.wrapper (<path>/node_modules/@google-cloud/promisify/build/src/index.js:30:35)
    at Topic.flush (<path>/node_modules/@google-cloud/pubsub/build/src/topic.js:116:24)
    at <path>/node_modules/@google-cloud/promisify/build/src/index.js:57:28
    at new Promise (<anonymous>)
    at Topic.wrapper (<path>/node_modules/@google-cloud/promisify/build/src/index.js:42:16)
```

I think the promisify need to use `.bind` to the queue:

https://github.com/googleapis/nodejs-pubsub/blob/cf3f31f70156a450054428aa1054e641af0d6531/src/publisher/index.ts#L105-L108

So should be (just a guess):

```ts
 const publishes = [promisify(this.queue.publish).bind(this.queue)()]; 
 Array.from(this.orderedQueues.values()).forEach(q => 
   publishes.push(promisify(q.publish).bind(q)()) 
 ); 
```

### PR DESCRIPTION
**Pull request by rhodgkins**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-pubsub/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- ~Appropriate docs were updated (if necessary)~

Fixes #1178 🦕

### CODE REVIEW

**Comment by rhodgkins** [comment]
Happy to amend fix commit message to pass conventional commits if someone wants to point me in the right direction with a good message!

**Comment by feywind** [comment]
@rhodgkins Thanks for the PR! I want to give the test changes some attention but it generally looks fine.

For conventional commits, for something like this I'd use something like:

`fix: bind promisify calls for flush() so they have a 'this' value`

**Comment by feywind** [comment]
@rhodgkins Can you go ahead and merge the latest changes from the master branch? It looks like I can't do it on your behalf.

**Comment by rhodgkins** [comment]
@feywind done! (eventually!)

**Review by feywind — APPROVED** [review]

**Comment by rhodgkins** [comment]
Thanks @feywind - any ideas on when the next release will be out?

**Pull request merged**
