### PR TITLE
test: fix import sample failures

### PR DESCRIPTION
**Pull request by JustinBeckwith**

### CODE REVIEW

**Comment by stephenplusplus** [comment]
I think this will fix #219!

**Comment by JustinBeckwith** [comment]
Pretty sure it won't :) I was running into some weird `replaceProjectIdToken` bugs even with that fix.  @crwilcox I remember you mentioning these elsewhere as well - am I misremembering?

**Comment by stephenplusplus** [comment]
Can we merge this and see what we get? Is Kokoro failing a non-merger?

**Comment by JustinBeckwith** [comment]
Yeah, sorry, the kokoro things can be safely ignored right now.

**Pull request merged**
