### PR TITLE
feat: upgrade @opentelemetry/api to version 0.20.0

### LINKED ISSUE #1304: Upgrade to @opentelemetry/api to latest version (0.20.0)
Thanks for stopping by to let us know something could be better!

 **Is your feature request related to a problem? Please describe.**
Upgrade opentelemetry packges to their respectiv elatest versions

 **Describe the solution you'd like**
Upgrade the repostiory :)

 **Describe alternatives you've considered**
None, it's an existing dependency

 **Additional context**
Existing dependency that wants to be upgraded :)

### PR DESCRIPTION
**Pull request by weyert**
Updates the Opentelemetry packages to the latest version and updated the
code to reflect the API changes

This should closely resemble the API of 1.0.0 of the package which is expected
to be released shortly.

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [X] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-pubsub/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [X] Ensure the tests and linter pass
- [X] Code coverage does not decrease (if any source code was changed)
- [X] Appropriate docs were updated (if necessary)

Fixes #1304 🦕

### CODE REVIEW

**Comment by tapico-weyert** [comment]
@googlebot I consent.

**Review by naseemkullah — APPROVED** [review]

**Comment by weyert** [comment]
there is a plan to release 1.0.0 of the `@opentelemetry/api` within days. Would be possible to do a release once this becomes available? My understanding is that this will be a safe version

**Comment by weyert** [comment]
Updated it with 1.0.0 of @opentelemetry/api :)

**Comment by feywind** [comment]
Awesome, thank you as always :) Let's see if we can get the tests unblocked...

**Review by feywind — APPROVED** [review]
I'm guessing we'll have to go with 0.20.0 until the other dependencies catch up and depend on 1.0.0, but that should be a pretty trivial change, looks like.

**Comment by weyert** [comment]
Awesome, that works for me! I did notice a 0.21 got released but think 0.20 should be fine: https://github.com/open-telemetry/opentelemetry-js/pull/2269/files 

I will raise  a new PR when the other dependencies are sorted out :) 

Thanks for meting 🤗

**Comment by feywind** [comment]
Oops, I forgot the Kokoro force-run.

**Pull request merged**
