### PR TITLE
propagate set options to LeaseManager

### LINKED ISSUE #1879: calling setOptions on subscriber does not take effect
if changing flowControl settings after calling .on they dont not get into effect

```
const subscription = pubSubClient.subscription(subscriptionNameOrId);
const messageHandler = message => {

  message.ack();
};

subscription.on('message', messageHandler);

// does not have any effect on flow control
subscription.setOptions({
flowControl: {
          maxMessages: 1,
          allowExcessMessages: true,
 }
})

```

### PR DESCRIPTION
**Pull request by dermasmid**
Fixes #1879

### CODE REVIEW

**Comment by feywind** [comment]
@dermasmid Thanks for the PR! I have a few things in my queue to do and then I'll look in more depth.

**Comment by swarmiakimmo** [comment]
Just wanted mention that this affects our use case as well. cc @feywind

**Comment by feywind** [comment]
@dermasmid Same on this PR, can you enable the allow maintainers to push flag?

**Comment by feywind** [comment]
Moved to https://github.com/googleapis/nodejs-pubsub/pull/1954

**Pull request closed without merging**
